import env from "./config/env.js";
import { collectPolicyWarnings } from "./governance.js";

function quoteIdentifier(value) {
  return /^[a-z_][a-z0-9_]*$/i.test(value) ? value : `"${String(value).replaceAll('"', '""')}"`;
}

function aliasFor(tableName) {
  return tableName.slice(0, 3);
}

function buildSelectList(plan) {
  if (plan.metrics?.length) {
    return plan.metrics.map((metric) => metric.expression).join(",\n  ");
  }

  const projectedColumns =
    plan.columns?.length > 0
      ? plan.columns.map((column) => {
          const alias = aliasFor(column.tableName);
          return `${alias}.${quoteIdentifier(column.columnName)}`;
        })
      : plan.tables.flatMap((table) => {
          const alias = aliasFor(table.tableName);
          return (table.primaryKeys ?? []).map((column) => `${alias}.${quoteIdentifier(column)}`);
        });

  if (projectedColumns.length === 0) {
    return null;
  }

  return [...new Set(projectedColumns)].join(",\n  ");
}

function buildFromClause(plan) {
  if (!plan.tables?.length) {
    return null;
  }

  const [firstTable, ...remainingTables] = plan.tables;
  let sql = `${quoteIdentifier(firstTable.schemaName)}.${quoteIdentifier(firstTable.tableName)} AS ${aliasFor(firstTable.tableName)}`;
  const joinedTables = new Set([firstTable.tableName]);

  for (const table of remainingTables) {
    const join = plan.joins.find((candidate) => {
      const connectsSource = joinedTables.has(candidate.sourceTable) && candidate.targetTable === table.tableName;
      const connectsTarget = joinedTables.has(candidate.targetTable) && candidate.sourceTable === table.tableName;
      return connectsSource || connectsTarget;
    });

    if (!join) {
      return null;
    }

    const leftAlias = aliasFor(join.sourceTable);
    const rightAlias = aliasFor(join.targetTable);
    sql += `\nJOIN ${quoteIdentifier(table.schemaName)}.${quoteIdentifier(table.tableName)} AS ${aliasFor(table.tableName)}`;
    sql += `\n  ON ${leftAlias}.${quoteIdentifier(join.sourceColumn)} = ${rightAlias}.${quoteIdentifier(join.targetColumn)}`;
    joinedTables.add(table.tableName);
  }

  return sql;
}

export function generateSqlDraft(plan, { question }) {
  if (!plan.isValid) {
    return {
      status: "validation_failed",
      text: "",
      warnings: plan.validationErrors
    };
  }

  const selectList = buildSelectList(plan);
  const fromClause = buildFromClause(plan);

  if (!selectList || !fromClause) {
    return {
      status: "not_generated",
      text: "",
      warnings: ["Unable to generate safe SQL because required tables, columns, or join paths are incomplete."]
    };
  }

  const { policyWarnings, sensitiveFields } = collectPolicyWarnings(plan, plan.__tableCatalog ?? []);
  const comments = [
    "-- Metadata-grounded SQL draft generated by telco-agentic-metadata-poc",
    `-- Question: ${question}`,
    "-- This SQL is not executed against a warehouse in the demo.",
    ...(sensitiveFields.length
      ? ["-- Sensitive fields referenced:", ...sensitiveFields.map((field) => `--   ${field.tableName}.${field.columnName} (${field.classification})`)]
      : [])
  ];

  const whereClause =
    plan.filters?.length > 0
      ? `\nWHERE\n  ${plan.filters.map((filter) => filter.expression).join("\n  AND ")}`
      : "";

  const limit = env.queryLimitDefault;

  return {
    status: "generated",
    text: `${comments.join("\n")}\nSELECT\n  ${selectList}\nFROM ${fromClause}${whereClause}\nLIMIT ${limit};`,
    warnings: policyWarnings
  };
}

export function attachCatalogToPlan(plan, tableCatalog) {
  plan.__tableCatalog = tableCatalog;
  return plan;
}
